In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.ones(shape = (5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.zeros(shape = (5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# Pour acceder  aux elements de notre matrice avec les outils de array
a = np.ones(shape = (4,4))

In [6]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
a[3,2] = 999

In [8]:
a

array([[  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1., 999.,   1.]])

In [9]:
a[3, ]      # Ici ca nous affiche tout la ligne 4 de notre matrice car elles sont comptées de 0 a 3 pour faire 4

array([  1.,   1., 999.,   1.])

In [10]:
a[:,2]

array([  1.,   1.,   1., 999.])

**Exercice**
La matrice suivante est dite diagonale par blocs parce que chaque bloc de 3x3 contient le même chiffre.

```
              [1, 1, 1, 0, 0, 0]
              [1, 1, 1, 0, 0, 0]
              [1, 1, 1, 0, 0, 0]
              [0, 0, 0, -1, -1, -1]
              [0, 0, 0, -1, -1, -1]
              [0, 0, 0, -1, -1, -1]
```

*  En utilisant le constructeur `np.array` et cette matrice comme argument, créez une nouvelle instance de `array` et assignez là à la variable X.

*  Recréez cette matrice en utilisant le slicing. Pour cela,
  1.  Créez une matrice de taille 6x6 pleine de zéros. Vous pourrez utilisez le constructeur `np.zeros` pour cela. Notez qu'il se comporte exactement comme le constructeur `np.ones` qu'on a vu en cours.
  2. En utilisant le slicing,
    - assignez au premier bloc 3x3 la valeure 1
    - Assignez au dernier bloc 3x3 la valeur 1

In [11]:
# créons cette matrice avec array
x = np.array([
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [0, 0, 0, -1, -1, -1],
    [0, 0, 0, -1, -1, -1],
    [0, 0, 0, -1, -1, -1]
])

In [12]:
x

array([[ 1,  1,  1,  0,  0,  0],
       [ 1,  1,  1,  0,  0,  0],
       [ 1,  1,  1,  0,  0,  0],
       [ 0,  0,  0, -1, -1, -1],
       [ 0,  0,  0, -1, -1, -1],
       [ 0,  0,  0, -1, -1, -1]])

In [13]:
# Creons une matrice 6x6 plaine de 0

np.zeros(shape = (6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
# en Utilisant le slicing ajoutons des matrices de 3x3 de 1 au premier et dernier bloc

premier_bloc = np.zeros(shape = (6,6)) # On affecte notre matrice de 6x6 de 0 a la variable premier_bloc

In [15]:
premier_bloc[0:3,0:3] = np.ones(shape= (3,3)) # Ici on dit a l'aide de [0:3,0:3] que nous situes sur les 3ere lignes et colones on dit quon affectes une matrice 3x3 de 1

In [16]:
premier_bloc # On affiche premier_bloc où la 1ere, 2e, 3e lignes et colones  ont été remplacés par 1, 1, 1

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
premier_bloc[3:6,3:6] = np.ones(shape = (3,3)) # Cest le meme principe ici on cherche les 3 dernieres lignes et 3 dernieres colonnes pour remplacer par np.onces(shapes=(3,3)) qui donne une matrice 3x3 de 1

In [18]:
premier_bloc

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [19]:
# Une autre methode pour faire cet exercice
# Creation de la matrice dim 6
A = np.array([[1, 1, 1, 0, 0, 0],
              [1, 1, 1, 0, 0, 0],
              [1, 1, 1, 0, 0, 0],
              [0, 0, 0, -1, -1, -1],
              [0, 0, 0, -1, -1, -1],
              [0, 0, 0, -1, -1, -1]])
# Creation d'une matrice de dimensions 6  remplies de zeros
A = np.zeros(shape = (6,6))

In [20]:
A

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
# Assignation de la valeur 1 au premier bloc
A[:3,:3] = 1

In [22]:
A

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
# Assignation de la valeur -1 au second bloc diagonal
A[3:,3:] = -1

In [43]:
A

array([[ 1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1., -1., -1.],
       [ 0.,  0.,  0., -1., -1., -1.],
       [ 0.,  0.,  0., -1., -1., -1.]])

In [25]:
# Affichage de la matrice
print(A)

[[ 1.  1.  1.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.]
 [ 0.  0.  0. -1. -1. -1.]
 [ 0.  0.  0. -1. -1. -1.]
 [ 0.  0.  0. -1. -1. -1.]]


In [26]:
                                            # FIN EXERCICE SUR  Création et Indexation

* EXERCICE 2
* (b) À l'aide des constructeurs et du slicing des arrays, créer et afficher la matrice suivante :



```
              [0, 1, 2, 3, 4, 5],
              [0, 1, 2, 3, 4, 5],
              [0, 1, 2, 3, 4, 5],
              [0, 1, 2, 3, 4, 5],
              [0, 1, 2, 3, 4, 5]
```

Indices:
  - Pour cela, essayez de ne pas recopier les valeurs directement dans le constructeur
  - Vous pouvez par exemple commencer à partir d'une matrice 6x6 pleine de 0
  - Remarquer, par exemple, que les colonnes vont de 0 à 5 et que vous savez générez ce genre de suite de chiffres entiers

In [27]:
X = np.zeros([6,6])
X

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
X[0:, 0:] = range(6)
X

array([[0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.]])

In [29]:
# Deuxieme methode
B = np.zeros(shape = (6,6))
for i in range(6):
    B[:, i] = i
print(B)
    

[[0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]]


In [30]:
# Troisieme solution
M = np.zeros(shape = (6, 6))

# On remplace chaque ligne par 'np.array([0, 1, 2, 3, 4, 5])''
for i in range(6):
    M[i,:] = np.array([0, 1, 2, 3, 4, 5])

# Affichage de la matrice
print(M)

[[0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]]


Opération sur les array

Le module numpy contient des fonctions mathématiques de base telles que :

| Fonction                 | Fonction Numpy       |
|--------------------------|----------------------|
| exp(x)                   | np.exp(x)            |
| log(x)                   | np.log(x)            |
| sin(x)                   | np.sin(x)            |
| cos(x)                   | np.cos(x)            |
| Arrondi à n décimales    | np.round(x, decimals=n) |

In [31]:
x = np.array([_/100 for _ in range(300)])
x

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09,
       1.1 , 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 ,
       1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31,
       1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42,
       1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.

In [32]:
np.exp(x)

array([ 1.        ,  1.01005017,  1.02020134,  1.03045453,  1.04081077,
        1.0512711 ,  1.06183655,  1.07250818,  1.08328707,  1.09417428,
        1.10517092,  1.11627807,  1.12749685,  1.13882838,  1.1502738 ,
        1.16183424,  1.17351087,  1.18530485,  1.19721736,  1.2092496 ,
        1.22140276,  1.23367806,  1.24607673,  1.25860001,  1.27124915,
        1.28402542,  1.29693009,  1.30996445,  1.32312981,  1.33642749,
        1.34985881,  1.36342511,  1.37712776,  1.39096813,  1.40494759,
        1.41906755,  1.43332941,  1.44773461,  1.46228459,  1.47698079,
        1.4918247 ,  1.50681779,  1.52196156,  1.53725752,  1.55270722,
        1.56831219,  1.58407398,  1.59999419,  1.6160744 ,  1.63231622,
        1.64872127,  1.66529119,  1.68202765,  1.69893231,  1.71600686,
        1.73325302,  1.7506725 ,  1.76826705,  1.78603843,  1.80398842,
        1.8221188 ,  1.8404314 ,  1.85892804,  1.87761058,  1.89648088,
        1.91554083,  1.93479233,  1.95423732,  1.97387773,  1.99

In [33]:
print(x.ndim)

1


Exercice 1. sur les operations sur les array

* (a) Définir une fonction f prenant en argument un array X et permettant de calculer en une seule ligne de code la fonction suivante :
> f(x)=exp(sin(x)+cos(x))


* (b) Afficher les 10 premiers éléments du résultat arrondi à 2 décimales de la fonction f appliquée à l'array X ci-dessous  

In [34]:
# On affiche notre matrice de 0, 0.01, 0.02 etc... jusqua 100 elements du meme format
X = np.array([i/100 for i in range(100)])
print(X)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]


In [35]:
# On definit une fonction f(X) et on retourne ce quelle devra faire

def f(X):
    return np.exp(np.sin(X) + np.cos(X))

print(f(X))

[2.71828183 2.74546328 2.7726365  2.79979313 2.8269247  2.85402258
 2.88107805 2.90808226 2.93502626 2.96190097 2.98869723 3.01540575
 3.04201719 3.06852207 3.09491088 3.12117399 3.14730172 3.17328432
 3.19911198 3.22477484 3.25026298 3.27556645 3.30067526 3.32557941
 3.35026887 3.37473358 3.39896349 3.42294856 3.44667875 3.47014403
 3.4933344  3.51623989 3.53885058 3.56115657 3.58314805 3.60481525
 3.62614847 3.6471381  3.66777461 3.68804857 3.70795064 3.72747161
 3.74660237 3.76533394 3.78365748 3.80156429 3.81904581 3.83609366
 3.8526996  3.86885558 3.8845537  3.89978629 3.91454584 3.92882505
 3.94261683 3.9559143  3.96871081 3.98099992 3.99277543 4.00403139
 4.01476208 4.02496203 4.03462604 4.04374914 4.05232666 4.06035417
 4.06782754 4.0747429  4.08109667 4.08688554 4.0921065  4.09675684
 4.10083414 4.10433625 4.10726136 4.10960793 4.11137473 4.11256083
 4.11316563 4.11318879 4.1126303  4.11149047 4.10976988 4.10746944
 4.10459035 4.10113412 4.09710256 4.09249777 4.08732214 4.0815

In [36]:
# On arrondi les 10 premiers elements a 2 chiffres apres la virgule

result = f(X)

valeur_arrondi = np.round(result, decimals = 2) # On rappelle que la syntaxe doit etre np.round(nom_var, decimals = nombre de chiffre après la virgule)

print(valeur_arrondi[:10]) # L indexation fonctionne bien ici et pour acceder aux 10 premiers elements on a :10


[2.72 2.75 2.77 2.8  2.83 2.85 2.88 2.91 2.94 2.96]


* (c) Définir une fonction f_python qui effectue la même opération sur chaque élément de X à l'aide d'une boucle for.
> Les dimensions d'un array X peuvent être récupérées à l'aide de l'attribut shape de X qui est un tuple : shape = X.shape.
>
> Pour un array à une dimension, le nombre d'éléments contenus dans cet array correspond au premier élément de sa shape : n = X.shape[0].

In [37]:
une_liste = [i/100 for i in range(100)]
#une_liste

In [38]:
# Ici on utilise la defintion de la fonction et on utilise la boucle for 
import math

def f_python():
    
    resultats = []
    
    for i in une_liste:
        
        resultat = math.exp(math.sin(i) + math.cos(i))
        
        resultats.append(resultat)
        
    return resultats
#print(f_python())

In [39]:
# Autre methode en utilisant les listes , celle ci utilise la comprehension de liste

import math

une_liste = [i / 100 for i in range(100)]

f_python = [math.exp(math.sin(i) + math.cos(i)) for i in une_liste]

# print(f_python)

In [40]:
# Les deux versions ci dessus sont juste mais on na pas utilisé X.shape

def f_python(X):
    
    n = X.shape[0]
    
    for i in range(n):
        
        X[i] = np.exp(np.sin(X[i]) + np.cos(X[i]))
print(X)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]


In [41]:
n = X.shape[0]
n

100

Exemple de la rapidité d'exécution sur un array de 10M de valeurs

Test de comparaison à faire avec une boucle for

In [42]:
from time import time

# Création d'un array à 10 millions de valeurs
X = np.array([i/1e7 for i in range(int(1e7))])

heure_debut = time()
f(X)
heure_fin = time()

temps = heure_fin - heure_debut

print("Le calcul de f avec une boucle for a pris", temps, "secondes")

Le calcul de f avec une boucle for a pris 2.991016387939453 secondes


# Support - Manipulation: indexation conditionnelle d'un array
 Une technique plus avancée pour l indexation des array 
 + Création d'un array de dimension 3x3
X = np.array([[-1, 0, 30],
              [-2, 3, -5],
              [5, -5, 10]])
On assigne a tous les elements neg la valeur 0


In [44]:
P = np.array([[-1, 0, 30],
              [-2, 3, -5],
              [5, -5, 10]])

In [49]:
P[P<0] = 0
P

array([[ 0,  0, 30],
       [ 0,  3,  0],
       [ 5,  0, 10]])