In [5]:
import numpy as np

* Nous disposons de données d'un supermarché américain qui se prépare pour le Black Friday, une journée où les commerces américains proposent de très grandes réduction pour finir leurs saisons.

Ces données sont distribuées sur 3 arrays :

>* items : Le nom des objets qui seront en promotion.
* quantities : Le stock disponible pour chaque objet en promotion.
* discounts : La réduction de prix de chaque objet. Les objets peuvent avoir une réduction de 25, 50, 75 ou 90 pourcents.

* Lancer la cellule suivante pour instancier les arrays contenant les données du supermarché

In [9]:
items = np.array(["grid paper","plate","rubber band","key chain","bread","speakers","chocolate",
                  "fridge","bowl","shirt","truck","canvas","monitor","piano","sailboat","clamp",
                  "spring","picture frame","knife","hanger","pool stick","buckel","vase","wagon",
                  "balloon","thread","couch","drawer","packing peanuts","bottle","needle",
                  "rusty nail","blanket","lamp","box","cookie jar","washing machine","paint brush",
                  "puddle","sketch pad","sandal","doll","floor","sidewalk","sand paper","stockings",
                  "bag","perfume","magnet","fake flowers","street lights","carrots","purse","thermostat",
                  "candle","mouse pad","remote","clothes","rubber duck","hair brush","computer","toe ring",
                  "scotch tape","nail file","window","table","model car","toothbrush","shoes","leg warmers",
                  "cat","pillow","rug","hair tie","phone","tooth picks","brocolli","newspaper","towel",
                  "watch","lotion","apple","pants","air freshener","pen","lace","car","headphones",
                  "charger","toilet","candy wrapper","soy sauce packet","sticky note","shoe lace",
                  "zipper","soda can","bed","cell phone","lip gloss","thermometer"])

quantities = np.array([310, 455, 295, 613, 812, 907, 564, 904, 829, 167, 517, 272, 416,
                       14, 251, 476, 757, 343, 472,  71, 160, 996, 182, 721, 565, 582,
                       279,  66, 297, 800, 914,  69, 498, 885, 114, 876, 635, 295, 146,
                       601, 941, 100, 370, 467, 423, 101, 504, 298, 757, 291, 163, 970,
                       921, 953, 458, 381, 692, 393, 749, 285, 454, 174,  37, 289, 863,
                       885, 331, 585, 678, 834, 349, 732, 149, 486, 993, 869, 967, 537,
                       220,  15, 457, 483, 387, 180, 579, 155, 134, 163, 314, 334, 429,
                       154,  18, 426, 363, 146, 454, 902, 145,  95])

discounts = np.array([25, 25, 50, 25, 50, 50, 50, 25, 50, 50, 25, 25, 25, 25, 50, 75, 25,
                      50, 50, 50, 25, 25, 25, 25, 75, 50, 25, 25, 25, 25, 90, 50, 25, 25,
                      25, 50, 50, 25, 25, 75, 75, 50, 25, 25, 50, 25, 90, 90, 50, 90, 25,
                      25, 25, 25, 25, 25, 25, 50, 25, 25, 75, 50, 50, 25, 50, 25, 25, 50,
                      25, 75, 25, 25, 50, 25, 25, 50, 75, 25, 25, 90, 25, 75, 25, 25, 25,
                      25, 25, 25, 50, 50, 75, 25, 50, 25, 25, 50, 25, 25, 25, 75])

* À l'aide d'une indexation conditionnelle sur items et quantities, afficher le nom et la quantité des objets qui auront une réduction de 90%.

In [11]:
reduction = discounts == 90
items_filtres = items[reduction]
quantities_filtres = quantities[reduction]
print(f"les objets {items_filtres} ayant des quantités respectives de {quantities_filtres} auront des reductions de 90%")


les objets ['needle' 'bag' 'perfume' 'fake flowers' 'watch'] ayant des quantités respectives de [914 504 298 291  15] auront des reductions de 90%


Vous voulez vous acheter un nouveau téléphone portable ("cell phone") et des enceintes sonores ("speakers").

* Déterminer à l'aide d'une indexation conditionnelle sur discounts la réduction qui leur sera accordée.

In [22]:
reduction_telephone = discounts[items == 'cell phone']
print(reduction_telephone[0])

25


In [23]:
reduction_enceinte = discounts[items == 'speakers']
print(reduction_enceinte[0])

50


In [27]:
petite_quantite = items[quantities < 50]
print(petite_quantite)

['piano' 'scotch tape' 'watch' 'sticky note']


In [33]:
reductions = discounts[quantities < 50]
print(reductions)

[25 50 90 50]


In [35]:
print(items[quantities < 50], discounts[quantities < 50])

['piano' 'scotch tape' 'watch' 'sticky note'] [25 50 90 50]


# Exercice : Articles en Promotion
Tu travailles sur une base de données contenant des articles, leurs prix et leurs stocks. Ton objectif est de trouver et afficher les articles qui sont en rupture de stock ou qui ont un prix inférieur à 20 €.

Données :
+ articles = np.array(["Ordinateur", "Téléphone", "Casque", "Clavier", "Souris", "Écran"])

+ prix = np.array([1200, 800, 15, 30, 10, 250])

+ stock = np.array([5, 2, 0, 10, 0, 3])

* Instructions :

Trouve les articles qui ont un stock de 0 (stock == 0).

Trouve les articles dont le prix est inférieur à 20 € (prix < 20).

Affiche les noms des articles concernés.

In [40]:
articles = np.array(["Ordinateur", "Téléphone", "Casque", "Clavier", "Souris", "Écran"])
prix = np.array([1200, 800, 15, 30, 10, 250])
stock = np.array([5, 2, 0, 10, 0, 3])
print(articles)
print(prix)
print(stock)

['Ordinateur' 'Téléphone' 'Casque' 'Clavier' 'Souris' 'Écran']
[1200  800   15   30   10  250]
[ 5  2  0 10  0  3]


In [51]:
print(articles[ stock == 0])

['Casque' 'Souris']


In [43]:
print(articles[prix<20])

['Casque' 'Souris']


In [47]:
print(f"Articles en rupture de stock: {articles[ stock == 0]} \nArticles à moins de 20 euros: {articles[prix < 20]}")

Articles en rupture de stock: ['Casque' 'Souris'] 
Articles à moins de 20 euros: ['Casque' 'Souris']


In [52]:
print(f"Articles en rupture de stock: {', '.join(articles[ stock == 0])} \nArticles à moins de 20 euros: {', '.join(articles[prix < 20])}")

Articles en rupture de stock: Casque, Souris 
Articles à moins de 20 euros: Casque, Souris


# Exercice Avancé : Analyse des Ventes

Tu travailles sur un tableau contenant des articles, leurs prix, leurs stocks, et le nombre d'unités vendues.

import numpy as np

articles = np.array(["Ordinateur", "Téléphone", "Casque", "Clavier", "Souris", "Écran"])

prix = np.array([1200, 800, 15, 30, 10, 250])  # Prix en euros

stock = np.array([5, 2, 0, 10, 0, 3])  # Stock restant

ventes = np.array([50, 40, 200, 150, 300, 80])  # Nombre d'unités vendues

+ Objectifs :

1. Affiche les articles qui ont un stock inférieur à 5 et un prix supérieur à 100 €.

2. Affiche les articles les plus populaires (ventes > 100 unités).

3. Calcule et affiche le chiffre d'affaires total (somme des ventes × prix).

4. Trouve l’article ayant généré le chiffre d’affaires le plus élevé.

5. Trouve l’article ayant le pire taux de vente (ventes / (ventes + stock)) et affiche son nom.

* Indice : Utilise np.argmax() et np.argmin() pour trouver les articles avec les valeurs max et min.

* Défi Bonus :
Ajoute une remise de 10% sur les articles ayant un stock supérieur à 5 et affiche leurs nouveaux prix.

In [53]:
articles = np.array(["Ordinateur", "Téléphone", "Casque", "Clavier", "Souris", "Écran"])

prix = np.array([1200, 800, 15, 30, 10, 250])  # Prix en euros

stock = np.array([5, 2, 0, 10, 0, 3])  # Stock restant

ventes = np.array([50, 40, 200, 150, 300, 80])  # Nombre d'unités vendues

In [71]:
faible_stock_cher = (stock < 5) & (prix >100) 
mask = articles[faible_stock_cher]
print(f"Articles avec faible stock et prix élevé : {', '.join(mask)}")


Articles avec faible stock et prix élevé : Téléphone, Écran


In [74]:
populaire = articles[ ventes > 100]
print(f"Articles populaires: {', '.join(populaire)}")

Articles populaires: Casque, Clavier, Souris


In [76]:
prix_total = ventes * prix
chiffre_affaire = sum(prix_total)
print(chiffre_affaire)


122500
